### ISSUE TITLE
Gyroscope and Accelerometer sensor classes not in the `iDynTreeSensors` doxygen group

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#100]
See http://wiki.icub.org/codyco/dox/html/idyntree/html/group__iDynTreeSensors.html ? 

@naveenoid can you take care of this issue, using the doxygen tags as explained in https://github.com/robotology/idyntree/blob/e6097038c2463a5767ba19cd9155c54bfcbeaba2/doc/dev/faqs.md#how-to-add-a-class-or-a-function-to-a-component-documentation ?

**Comment by naveenoid** [comment]
https://github.com/robotology/idyntree/pull/101

**Comment by traversaro** [comment]
Fixed by #101 .

**Comment by traversaro** [comment]
The module tag ( `iDynTreeModelIO` ) is also missing for the sensor from urdf parser functions : http://wiki.icub.org/codyco/dox/html/idyntree/html/group__iDynTreeModelIO.html .

**Comment by traversaro** [comment]
@naveenoid https://github.com/robotology/idyntree/issues/100#issuecomment-161571290

**Comment by naveenoid** [comment]
Sorting out in master directly. Will keep developing my stuff in my branch

**Comment by traversaro** [comment]
:+1:
