### ISSUE TITLE
iDynTree Usage in MATLAB

### ISSUE THREAD

**Issue by yuying334** [robotology/idyntree#1034]
Hi, I am confused about the description " If this is not working, make sure that you are launching matlab after having activated the conda environment (if you installed iDynTree via conda)". which environment do you mean here? When I use IDynTree in Matlab by just add the folder path "D:\conda\conda\Library\mex" and it has problem with running "iDynTreeMEX".  The error message is "Invalid MEX-file mexfilename: The specified module could not be found." Could you help me or give a more detailed guidance for matalab usage. I am really appreciate for that.

**Comment by traversaro** [comment]
Hello @yuying334 !

That phrase means that everything works if you launch matlab from the Command Prompt in which you run `conda activate <nameofenv>`. If you prefer not to launch matlab from the Command Prompt, an alternative is to add to the path the necessary libraries directly via MATLAB, as we do for example in https://github.com/robotology/robotology-superbuild/blob/master/doc/matlab-one-line-install.md :

~~~
setenv("PATH",strcat("D:\conda\conda\Library\bin", ";", getenv("PATH")));
add_path("D:\conda\conda\Library\mex")
~~~

**Comment by yuying334** [comment]
> Hello @yuying334 !
> 
> That phrase means that everything works if you launch matlab from the Command Prompt in which you run `conda activate <nameofenv>`. If you prefer not to launch matlab from the Command Prompt, an alternative is to add to the path the necessary libraries directly via MATLAB, as we do for example in https://github.com/robotology/robotology-superbuild/blob/master/doc/matlab-one-line-install.md :
> 
> ```
> setenv("PATH",strcat("D:\conda\conda\Library\bin", ";", getenv("PATH")));
> add_path("D:\conda\conda\Library\mex")
> ```

Hello, 
Thanks a lot! It really helps me a lot.

**Comment by traversaro** [comment]
I see, probably we could add this to the docs, even if I am afraid it would become too complex.

**Comment by traversaro** [comment]
Hello @yuying334, do you think we can close this issue?

**Comment by yuying334** [comment]
Hello, yes of course, thank you

Silvio Traversaro ***@***.***>于2022年12月13日 周二12:46写道：
