### ISSUE TITLE
Handle `Irrlicht` limitation on the number of vertices rendered

### ISSUE THREAD

**Issue by mebbaid** [robotology/idyntree#1137]
Some models with particularly "dense" meshes in terms of number of vertices computed throw the following error when calling the `idyntree-yarp-visualizer -m model.urdf`

```
Too many vertices for 16bit index type, render artifacts may occur

```

This can be traced to this line https://github.com/zaki/irrlicht/blob/97472da9c22ae4a49dfcefb9da5156601fa6a82a/source/Irrlicht/CNullDriver.cpp#L808 upstream

This may lead to rendering models with missing parts/meshes.

**Comment by mebbaid** [comment]
Related PR is open in #1139

**Comment by traversaro** [comment]
Fixed by @mebbaid in https://github.com/robotology/idyntree/pull/1139 .
