### ISSUE TITLE
Add toVector method to SensorsMeasurements

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#122]
Add a method:
~~~
SensorsMeasurements::toVector(VectorDynSize & vec)
~~~
to the the SensorsMeasurements class, as discussed in https://github.com/robotology/idyntree/pull/104#issuecomment-163581506 .

**Comment by naveenoid** [comment]
https://github.com/robotology/idyntree/commit/6c2b937391f372235538154a1784c2161f11067b

**Comment by naveenoid** [comment]
@traversaro Please close this on merging the PR

**Comment by traversaro** [comment]
Closed by https://github.com/robotology/idyntree/pull/103 .
