### ISSUE TITLE
Problem in generating Matlab bindings with OS X

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#136]
cc @nunoguedelha

**Comment by traversaro** [comment]
I was able to replicate the problem with make, so apparently the problem is not in the xcode generator but on OS X.

**Comment by traversaro** [comment]
I suspect that there is a different behavior between related to the different version of CMake available on OS X and Ubuntu 14.04 .

**Comment by nunoguedelha** [comment]
I had take a look into the `bindings/Matlab/CMakeLists.txt` file and found some anomalies. I'm taking a look again this afternoon.

**Comment by traversaro** [comment]
I am debugging it right now.

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/idyntree/pull/142 .
