### ISSUE TITLE
getLink not working on Matlab

### ISSUE THREAD

**Issue by fjandrad** [robotology/idyntree#139]
When attempting to use model().getLink() on Matlab it returns:
 "Error using subsref
No appropriate method, property, or field 'getLink' for class 'iDynTree.Model'.

Error in SwigRef/subsref (line 29)
        [varargout{1:nargout}] = builtin('subsref',self,s);"
 And when checking the Model.m file in bindings getLink is not there as well as getJoint.
Both functions should return a pointer (either a linkpointer or a joint pointer).

**Comment by traversaro** [comment]
@fjandrad that should be fixed now.
