### ISSUE TITLE
CoM f.k. and jacobian

### ISSUE THREAD

**Issue by francesco-romano** [robotology/idyntree#144]
plus transformation from angular velocity to derivative of quaternion.

**Comment by francesco-romano** [comment]
and `getRelativeFrameJacobian`

**Comment by traversaro** [comment]
First COM-related methods added in https://github.com/robotology/idyntree/pull/146 .

**Comment by francesco-romano** [comment]
:+1:

**Comment by francesco-romano** [comment]
Adding other useful methods:

- Rotation::asQuaternion
- Sparsity pattern for Jacobian and Hessians

**Comment by traversaro** [comment]
What would be a good format for sparsity patterns (i.e. what is used by IPOPT?).

**Comment by francesco-romano** [comment]
From what I understood from the documentation the format is quite free, in the sense that the Jacobian is specified as a one-d vector.
Then the correspondence between position in the vector and in the original matrix is supplied by the user by filling two vector.
This example fills a dense matrix of 2 x 4:
```
// this particular Jacobian is dense
    iRow[0] = 0; jCol[0] = 0;
    iRow[1] = 0; jCol[1] = 1;
    iRow[2] = 0; jCol[2] = 2;
    iRow[3] = 0; jCol[3] = 3;
    iRow[4] = 1; jCol[4] = 0;
    iRow[5] = 1; jCol[5] = 1;
    iRow[6] = 1; jCol[6] = 2;
    iRow[7] = 1; jCol[7] = 3;
```
As you can see we are saying that the 8th position in the vector is the element (2,4) (one based in my 'math' description 😄 )

**Comment by traversaro** [comment]
Mhh, this seems a classical sparse matrix representation. Just for the sake of understanding, does IPOPT support both sparse (this one) matrices and dense matrices rappresentation or just this sparse one?

**Comment by traversaro** [comment]
If we are constrained to the sparse representation, I would go for writing a basic `iDynTree::MatrixSparse` class compatible with both IPOPT and [Eigen::Map<SparseMatrix>](https://eigen.tuxfamily.org/dox-devel/classEigen_1_1Map_3_01SparseMatrixType_01_4.html), and then let Eigen handle all the dirty job.

**Comment by francesco-romano** [comment]
I've no experience on sparse matrix representation, so I let you decide the format.

IPOpt support only this format. Thus you can fill a "dense-sparse" matrix :)

**Comment by francesco-romano** [comment]
First quaternion conversion implemented here: https://github.com/robotology/idyntree/pull/167

**Comment by traversaro** [comment]
I guess this issue was fixed in the end, feel free to open again otherwise.
