### ISSUE TITLE
Clean up 

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#19]
A clean up is currently undergoing in `development` branch (v0.3) to facilitate development, maintenance and dissemination (and to finally merge the new "floating position/velocity/acceleration/torque" logic. 

* [x] Get a basic example (compiled out of the superbuild and of iDynTree source tree) to work 
* [x] Get the codyco-superbuild to build and work with v0.3 (check that all test pass)
* [ ] Get the walkman superbuild to build and check that all tests are passing
* [x] Restore the iDyn / iDynTree consistency checks, use them also for check urdf export. 
* [x] Correctly compile and install useful tools:
 * [x] urdf2dh 
 * [x] par2urdf
 * [ ] urdf_get_mass

**Comment by traversaro** [comment]
Restored the iDyn/iDynTree consistency checks, there was a bug in assuming that the ft sensor frame was the one of parent link instead of the child link.

**Comment by francesco-romano** [comment]
- move all inclusions to .cpp files and use forward declarations
- transform all intra-library header inclusions to use quotes instead of angular brackets
- all intra-library inclusions should be "direct", i.e. #include "myHeader.h" vs #include "folder/myHeader.h"

**Comment by traversaro** [comment]
@francesco-romano (not worth doing that for things in the yarp directory, ok for everything else).

**Comment by traversaro** [comment]
@francesco-romano namespace of what? C++ namespace?

**Comment by francesco-romano** [comment]
@traversaro yes (and also some folder restructuring).
e.g.
`kdl_codyco` => `idyntree/core`

anyway I saw you already did some work on regressors, etc..

**Comment by traversaro** [comment]
Yes, most of the libraries are already in a namespace, we just need to appropriately change the name of the namespace.

**Comment by traversaro** [comment]
Update: most of the headers now use forward declarations when possible. 
All code in the library should be contained in the `iDynTree` namespace. 
Using additional namespaces have been discarded for being to complex and to match the package structure of Matlab and Python bindings. 

Legacy code ( former kdl_codyco, kdl_format_io) will not be updated because it will be deprecated by the pure-iDynTree (and thus with native bindings) implementations.
