### ISSUE TITLE
Understand why doxygen documentation of some KinDynComputations class methods related to dynamics is not appearing on the website

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#251]
See http://wiki.icub.org/codyco/dox/html/idyntree/html/classiDynTree_1_1KinDynComputations.html#ae5a13daafda43dd17c1def2441a1bba3 vs https://github.com/robotology/idyntree/blob/master/src/high-level/include/iDynTree/KinDynComputations.h#L555 .

**Comment by giuliavezzani** [comment]
Can someone assign it to me? I don't have the permission to self-assign it :smile:

**Comment by traversaro** [comment]
Done, thanks for the interest! : )

**Comment by traversaro** [comment]
Doxygen documentation of idyntree can be produced locally by using the `make dox` command.

**Comment by giuliavezzani** [comment]
Thanks for assigning to me! I'll face the problem asap :smiley:

**Comment by traversaro** [comment]
This is now working: https://robotology.github.io/idyntree/master/classiDynTree_1_1KinDynComputations.html#a9149e7d3dc280e3fd777998c465c9016 .
