### ISSUE TITLE
Remove dynamic memory allocation from KinDynComputations::getRelativeJacobian

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#271]
See https://github.com/robotology/idyntree/pull/270/files#diff-584f911921597b1810b3e44e82646f23R1029 .

**Comment by francesco-romano** [comment]
Why that line should generate a memory allocation?
I mean... if the user already provides a correct sized Jacobian that line should be a noop (from the memory allocation point of view)
Am I wrong?

**Comment by traversaro** [comment]
The original context was in https://github.com/robotology/idyntree/pull/270#discussion-diff-106100354R1028 , i.e. related to the traversal pool. I think this can be closed.

**Comment by francesco-romano** [comment]
ah right! sorry
