### ISSUE TITLE
Handle deprecated headers

### ISSUE THREAD

**Issue by diegoferigo** [robotology/idyntree#312]
Referring https://github.com/robotology/idyntree/pull/310, the kdl header deprecation warnings have been disabled upstream, but are kept enabled for downstream.

In order to avoid forgetting to handle them for the next release, here below a list of folders that contain code that links with them:

```
src
|-- estimation-kdl
|-- high-level-kdl
|-- icub-kdl
|-- kdl
|-- model_io
    `--urdf-kdl
|-- regressor
`-- yarp-kdl
```

**Comment by traversaro** [comment]
These headers were removed in https://github.com/robotology/idyntree/pull/697 .
