### ISSUE TITLE
Travis on idyntree is too slow

### ISSUE THREAD

**Issue by diegoferigo** [robotology/idyntree#313]
I plan to do sooner or later some docker magic to speed up the linux builds. Let me know if you have something against it.

**Comment by traversaro** [comment]
👍 

It would be great if we could maintain the macOS tests.

**Comment by diegoferigo** [comment]
@traversaro 
That's for sure, I'll handle this in the same way we do for other projects.

**Comment by diegoferigo** [comment]
Implemented in https://github.com/robotology/idyntree/pull/469 by @traversaro
