### ISSUE TITLE
Cleanup optimalcontrol component

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#400]
See comments to https://github.com/robotology/idyntree/pull/399/files .

**Comment by traversaro** [comment]
We should also remember to update the changelog ( https://github.com/robotology/idyntree/blob/devel/doc/releases/v0_10.md ) to mention the new optimal control classes and the modifications to the spline classes.

**Comment by traversaro** [comment]
Any idea about this comments @S-Dafarra : 
 * https://github.com/robotology/idyntree/pull/399/files#r155391525 
 * https://github.com/robotology/idyntree/pull/399/files#r155391745 

?

**Comment by S-Dafarra** [comment]
Regarding the first, I will delete that comment in a (near) future PR.

Regarding the second, I already changed it https://github.com/robotology/idyntree/blob/devel/src/optimalcontrol/tests/CMakeLists.txt

**Comment by traversaro** [comment]
All the comments fixed in `devel` .
