### ISSUE TITLE
[doc] documentation for Telerobot

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#41]
We need a:
 * [x] Documentation on how to install iDynTree without the `codyco-superbuild` but still retaining all the dependencies. iDynTree-superbuild could be a nice solution.  
 * [x] tutorial to cover:
   *  Load a URDF model to a class 
   * Compute the gravity terms for a fixed base robot, given the joint positions. 
Nice to have:
 * [x] Migrate to robotology/iDynTree

**Comment by iron76** [comment]
I guess also the third point has been accomplished :)
