### ISSUE TITLE
Release 0.11 

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#467]
We have a few fixes just in `devel` that it would be nice to have in master, and  some new features such as the new XML parser that it would be nice to release. I think we can proceed to release 0.11 relatively soon, any comment? 
@diegoferigo @DanielePucci @prashanthr05

**Comment by ahoarau** [comment]
maybe #383 :dancer:

**Comment by traversaro** [comment]
Ok!

**Comment by traversaro** [comment]
I think this can also be the last release compatible with YARP 2.3.72 .

**Comment by traversaro** [comment]
Sorry @ahoarau , we are kind in a hurry and I am going to release 0.11 now. I hope to get https://github.com/robotology/idyntree/issues/383 in 0.12 !

**Comment by ahoarau** [comment]
@traversaro No prob. Could you also mention the c++ version you use ? 11 ? 14 ?

**Comment by traversaro** [comment]
Good point. Since this release, we use C++14 in the headers, I will add that on the release notes.

**Comment by traversaro** [comment]
Done.
