### ISSUE TITLE
Expose iDynTree.InverseKinematics in Matlab bindings 

### ISSUE THREAD

**Issue by VenusPasandi** [robotology/idyntree#498]
The funcionality of the `iDynTree::InverseKinematics` class is quite useful, but at the moment it is not exposed in Matlab bindings. It would be convenient if this class could be exposed, and if an example could be available because the existing doxygen documentation is incomplete and confusing.

**Comment by lrapetti** [comment]
Bindings have been generated with https://github.com/robotology/idyntree/pull/633

**Comment by traversaro** [comment]
Addressed in https://github.com/robotology/idyntree/pull/633 by @lrapetti .
