### ISSUE TITLE
The default rotation parametrization of Inverse Kinematics uses quaternions but it causes Ipopt crashes

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/idyntree#514]
We (@Yeshasvitvs ) were facing a strange segfault problem when using the IK. [Here](https://github.com/Yeshasvitvs/human-dynamics-estimation/blob/17e345aae88a709a2e023a1d18071358b7bba450/devices/HumanStateProvider/tests/ipopt-test.cpp) the test. By adding the following line
```
ik.setRotationParametrization(iDynTree::InverseKinematicsRotationParametrizationRollPitchYaw);
```
it started working as expected. The problem is that by default ``iDynTree::InverseKinematicsRotationParametrizationQuaternion`` is used, as can be see [here](https://github.com/robotology/idyntree/blob/master/src/inverse-kinematics/src/InverseKinematicsData.cpp#L33).

Also, by using a verbose output, ``IPOPT``'s derivative checker find several issues.

**Comment by traversaro** [comment]
The derivative problem for quaternion is unfortunately a known issue, see https://github.com/robotology/idyntree/issues/282#issue-220883630, but indeed: 
* it is poorly documented
* the default choice should definitely be a working one, not the experimental one.
