### ISSUE TITLE
Adding RPYRightTrivializedSecondDerivative() into iDyntree::Rotation class

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/idyntree#540]
Checking `iDynTree` documentation seems that the second derivative of `RPYRightTrivialized` matrix is not implemented (see [here](http://wiki.icub.org/codyco/dox/html/idyntree/html/classiDynTree_1_1Rotation.html#ade94c567710848fe366c1554279f3c1e) for the first derivative). 
This new method can be useful for evaluating the angular acceleration from the Euler angle rate of change.

If you are interested I can propose a PR with the implementation 

cc @MiladShafiee @traversaro

**Comment by traversaro** [comment]
Yes I think it would make sense to have it.

**Comment by GiulioRomualdi** [comment]
Related PR #542

**Comment by traversaro** [comment]
Thanks, fixed in https://github.com/robotology/idyntree/pull/542 .
