### ISSUE TITLE
[yarprobotstatepublisher] The BottleImpl error flood

### ISSUE THREAD

**Issue by prashanthr05** [robotology/idyntree#550]
Whenever we run the `yarprobotstatepublisher` the following error floods the terminal

``` bash
yarp: BottleImpl reader failed, unrecognized object code 0
```

Any suggestions to fix this?

UPDATE: I think error is more related to the usage of YARP transform server.

**Comment by traversaro** [comment]
I have no idea why this happen. Have you tried to run a debugger to understand which line generates this error message?

**Comment by traversaro** [comment]
@prashanthr05 Are you still experiencing this? Do you know how to reproduce it?

**Comment by prashanthr05** [comment]
Unfortunately, I had not gone back to addressing/testing/reproducing this problem. Maybe we could close this issue at the moment, and reopen if this issue arises again.

**Comment by traversaro** [comment]
> Unfortunately, I had not gone back to addressing/testing/reproducing this problem. Maybe we could close this issue at the moment, and reopen if this issue arises again.

Ok!
