### ISSUE TITLE
Include ModelTestUtils.h to the installed files 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/idyntree#606]
It could be really useful to install also the `ModelTestUtils.h` file. Indeed, it will simplify the testing of some model-based algorithms.

However, as can be seen here the aforementioned header is considered private
https://github.com/robotology/idyntree/blob/c8bf721b771fa4b1e7c3a940632e121060719a19/src/model/CMakeLists.txt#L37

Is there a reason why the installation is prevented?

@traversaro

**Comment by GiulioRomualdi** [comment]
I can easily propose a PR

**Comment by traversaro** [comment]
No reason, I just thought it was not useful. Feel free to propose a PR thanks.

**Comment by GiulioRomualdi** [comment]
Fixed by #607
