### ISSUE TITLE
add vendored libxml2

### ISSUE THREAD

**Issue by ahoarau** [robotology/idyntree#634]
Now that we have a nice CMakeLists available at https://github.com/roboticslibrary/libxml2
What about adding libxml2 in the "extern" dir and build a private static lib ?
As far as I know, the use of libxml2 is only private in iDyntree

**Comment by traversaro** [comment]
I was thinking of adding an option of grabbing Eigen3 and LibXml2 via  FetchContent, would it be ok also that?

**Comment by ahoarau** [comment]
My dreams would come true !

**Comment by ahoarau** [comment]
iDyntree self contained for 1.2 ?

**Comment by traversaro** [comment]
> iDyntree self contained for 1.2 ?

Let's see, it is not difficult but I don't know when we will be working on it.

**Comment by ahoarau** [comment]
If neither eigen nor libxml2 appears in the public header, having it build by itself would be a great addition. Easier to install on embedded systems
