### ISSUE TITLE
Implement begin/end function for iDynTree vectors

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/idyntree#645]
Sometimes having `begin()` / `end()` member functions for `iDynTree` vectors may be really useful to iterate over them. 

Are you interested in a PR?

**Comment by traversaro** [comment]
Yes.

**Comment by GiulioRomualdi** [comment]
The feature has been implemented in https://github.com/robotology/idyntree/pull/646 Can we close the issue?

**Comment by traversaro** [comment]
Ok!
