### ISSUE TITLE
Improve the use of `const` in KinDynComputation

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/idyntree#687]
I noticed that some functions in `KinDynComputation` are not const even if they don't modify any member of the class. For instance the function [`bool iDynTree::KinDynComputations::getJointPos()`](https://robotology.github.io/idyntree/devel/classiDynTree_1_1KinDynComputations.html#a3154c238fcccc126e56d95e40e2fd832) is not considered as a `const` method.

**Comment by traversaro** [comment]
This change is an ABI-change, so I prefer to do that in iDynTree 2.0 (I would like to release at least the existing `devel` as iDynTree 1.1 before). However, if you could already list the methods that can me made `const` it would be helpful.

**Comment by traversaro** [comment]
I guess this was fixed in https://github.com/robotology/idyntree/pull/736, am I correct @GiulioRomualdi ?

**Comment by GiulioRomualdi** [comment]
In theory yes

**Comment by traversaro** [comment]
I am tempted to ask why "in theory", but probably is better just to close the issue.
