### ISSUE TITLE
Possible bug in iDynTree::Span

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/idyntree#729]
If I'm not mistaken here
https://github.com/robotology/idyntree/blob/f9fff5998c459dacf869629c3fe629d5831f240f/src/core/include/iDynTree/Core/Span.h#L498-L499

`double` should be substituted with `reference`.

**Comment by traversaro** [comment]
Good catch! Are you sure that `reference` is the correct fix? At a first glance I would say that `value_type` may be more in line with the semantics of the method.

**Comment by traversaro** [comment]
Friendly ping @GiulioRomualdi , I suspect that `value_type` may be indeed a better fix. As in any case it would be an API/ABI change, I suggest to do it in the `devel`  branch,

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/idyntree/pull/749 .
