### ISSUE TITLE
[IO] Denavit Hartenberg parameters export

### ISSUE THREAD

**Issue by traversaro** [robotology/idyntree#77]
@fiorisi reported a case in which a URDF Chain was converted to a DH with a non-identity H0, even if the DH chain could be expressed with a identity H0.

**Comment by traversaro** [comment]
@fiorisi Do you remember anything related to this? Now we completely rewrote the part of iDynTree handling DH parameters, so it is possible that this problem does not hold anymore.

**Comment by fiorisi** [comment]
Considering that was a long time ago and that you are updating the code, I think that we can close the issue.
