### ISSUE TITLE
Missing is/asPrismaticJoint in bindings

### ISSUE THREAD

**Issue by Nicogene** [robotology/idyntree#881]
It is possible to get the handle of the `RevoluteJoint` and `FixedJoint` using the (python) bindings thanks to

https://github.com/robotology/idyntree/blob/ab9336447ab0c6d6d9f9d0c3d3a19be31140aed3/bindings/joints.i#L15-L41

It would be nice if these can be extended to other types of joints, in particular I would be like to have `is/asPrismaticJoint`

**Comment by traversaro** [comment]
It should be sufficient to add the code similar to the revolute one for the other types, feel free to open a PR, thanks!
